config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :movies
    resources :categories
  end

  root to: 'movies#index'
  get '/:id', to: 'movies#show', as: :movie
  post '/movies/:id/rating', to: 'movies#rating', as: :movie_rating
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
end

app/models/movie.rb
class Movie < ApplicationRecord
  paginates_per 10
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :category
  has_many :ratings

  def average_rating
    ratings.average(:score) || 0
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: { member: 0, admin: 1}

  has_many :ratings
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to [:admin, @category], notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to [:admin, @category], notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < AdminController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to [:admin, @movie], notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to [:admin, @movie], notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to admin_movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :text, :category_id)
    end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
	before_action :authenticate_user!
	before_action :ensure_admin! 

	private 
	
	def ensure_admin!
		redirect_to root_path unless current_user&.admin?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :error_404

  private

  def error_404
    render 'application/error_404', status: 404
  end
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
  before_action :authenticate_user!, only: :rating
  def index
    @categories = Category.all
    @movies = (
      params[:category_id] ? Movie.where(category_id: params[:category_id]) : Movie
    ).page(params[:page])
  end

  def show
    movie
  end

  def rating
    movie.ratings.create(score: params[:rating], user: current_user)
    redirect_back fallback_location: root_path
  end

  private

  def movie
    @movie ||= Movie.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category], :html => { :class => "form-horizontal category" } do |f| %>

  <% if @category.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_categories_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/admin/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, admin_category_path(category) %></td>
        <td><%= category.title %></td>
        <td><%=l category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_category_path(category), :class => 'btn btn-default btn-xs' %>
          <%= button_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_category_path,
            :class => 'btn btn-primary' %>

app/views/admin/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @category.title %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_categories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_category_path(@category), :class => 'btn btn-default' %>
<%= button_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/admin/movies/_form.html.erb
<%= form_for [:admin, @movie], :html => { :class => "form-horizontal movie" } do |f| %>

  <% if @movie.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :text, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :text, :class => 'form-control' %>
    </div>
    <%=f.error_span(:text) %>
  </div>
  <div class="form-group">
    <%= f.label :category_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select :category_id, Category.all, :id, :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:category_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_movies_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/admin/movies/edit.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/movies/index.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:text) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.id, admin_movie_path(movie) %></td>
        <td><%= movie.title %></td>
        <td><%= movie.text %></td>
        <td><%= movie.category&.title %></td>
        <td><%=l movie.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_movie_path(movie), :class => 'btn btn-default btn-xs' %>
          <%= button_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_movie_path(movie),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_movie_path,
            :class => 'btn btn-primary' %>

app/views/admin/movies/new.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/movies/show.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @movie.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= @movie.text %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @movie.category_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_movies_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_movie_path(@movie), :class => 'btn btn-default' %>
<%= button_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_movie_path(@movie),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/application/error_404.html.erb
Page not found

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImdbClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to "Categories", admin_categories_path %>
          </li>
          <li>
            <%= link_to "Movies", admin_movies_path %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImdbClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', media: 'all'%>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Movies</a>
        </div>

        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li>
                <%= button_to "Sign Out", destroy_user_session_path, class: 'btn', method: :'delete' %>
              </li>
            <% else %>
              <li>
                <%= link_to "Sign In", new_user_session_path %>
              </li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2">
          <%= yield :sidebar %>
        </div>        
        <div class="col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/movies/index.html.erb
<%= content_for :sidebar do %>
    <div class="row">
      <div class="sidebar">
      <div class="mini-submenu">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </div>
      <div class="list-group">
          <span href="#" class="list-group-item">
              Categories
              <span class="pull-right">
                  <i class="fa fa-times"></i>
              </span>
          </span>
          <% @categories.each do |category| %>
            <%= link_to root_path(category_id: category.id), class: "list-group-item #{params[:category_id].to_i == category.id ? 'active' : '' }" do %>
                <i class="fa fa-comment-o"></i> <%= category.title %>
            <% end %>
          <% end %>
      </div>        
  </div>
    </div>
<% end %>

<% @movies.each do |movie|%>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
			<%= link_to movie.title, movie, class: 'card-link' %>
		</h3>
  </div>
  <div class="panel-body">
		<%= movie.text %>
  </div>
  <% if current_user && !current_user.ratings.exists?(movie_id: movie.id) %>
    <div class="panel-footer">
      <div class="ratings">
        <% 10.downto(1) do |n| %>
          <%= button_to movie_rating_path(movie), remote: true, params: { rating: n }, title: "#{n} stars", class: 'btn btn-default btn-grey btn-sm star' do %>
            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
          <% end %>
        <% end %>

      </div>
    </div>
  <% end %>
</div>
<% end %>

<%= paginate @movies, theme: 'twitter-bootstrap-4' %>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
			<%= link_to @movie.title, @movie, class: 'card-link' %>
		</h3>
  </div>
  <div class="panel-body">
		<%= @movie.text %>
  </div>
  <div class="panel-footer">
    <h4>Average user rating</h4>
    <h2 class="bold padding-bottom-7"><%= @movie.average_rating %> <small>/ 10</small></h2>
  </div>
</div>